/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-bright': '#2c2c2c',
        'on-primary-fixed-variant': '#006a2b',
        'on-secondary-container': '#e2ffe9',
        'on-secondary': '#005e39',
        'surface': '#0e0e0e',
        'error-container': '#b92902',
        'primary-fixed-dim': '#63ef82',
        'surface-variant': '#262626',
        'surface-container-highest': '#262626',
        'on-background': '#ffffff',
        'surface-container-high': '#20201f',
        'primary-fixed': '#72fe8f',
        'on-tertiary-container': '#004d58',
        'surface-container-low': '#131313',
        'surface-container': '#1a1a1a',
        'error': '#ff7351',
        'secondary': '#7cfbb5',
        'primary-dim': '#63ef82',
        'outline-variant': '#484847',
        'background': '#0e0e0e',
        'secondary-dim': '#6deca8',
        'on-primary': '#005f26',
        'outline': '#767575',
        'surface-tint': '#72fe8f',
        'on-surface': '#ffffff',
        'surface-container-lowest': '#000000',
        'inverse-surface': '#fcf9f8',
        'error-dim': '#d53d18',
        'on-error': '#450900',
        'primary-container': '#1cb853',
        'on-surface-variant': '#adaaaa',
        'inverse-primary': '#006e2d',
        'on-primary-container': '#002a0c',
        'on-error-container': '#ffd2c8',
        'primary': '#72fe8f',
        'surface-dim': '#0e0e0e',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
